### ISSUE TITLE
Able to click Next when supporting files are uploading

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1361]
On the "Submission" page if you complete the cover letter and upload a manuscript... then start an upload(s) of supporting files .... you are able to click "Next" and go on to complete the submission.

This results in an error on the MECA export as the file is not found in S3...

```

info: Starting MECA export manuscriptId=5c5c07f1-15af-4b41-9bbe-188fa40a3c77
error: MECA export failed message=The specified key does not exist., stack=NoSuchKey: The specified key does not exist.
    at Request.extractError (/home/xpub/node_modules/aws-sdk/lib/services/s3.js:582:35)
    at Request.callListeners (/home/xpub/node_modules/aws-sdk/lib/sequential_executor.js:109:20)
    at Request.emit (/home/xpub/node_modules/aws-sdk/lib/sequential_executor.js:81:10)
    at Request.emit (/home/xpub/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/xpub/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/xpub/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/xpub/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/xpub/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/xpub/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/xpub/node_modules/aws-sdk/lib/sequential_executor.js:119:18)
    at Request.emit (/home/xpub/node_modules/aws-sdk/lib/sequential_executor.js:81:10)
    at Request.emit (/home/xpub/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/xpub/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/xpub/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/xpub/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/xpub/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/xpub/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/xpub/node_modules/aws-sdk/lib/sequential_executor.js:119:18)
    at callNextListener (/home/xpub/node_modules/aws-sdk/lib/sequential_executor.js:99:12)
    at IncomingMessage.onEnd (/home/xpub/node_modules/aws-sdk/lib/event_listeners.js:294:13)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7), code=NoSuchKey, region=null, name=NoSuchKey, time=Tue Jan 22 2019 09:39:57 GMT+0000 (UTC), requestId=C21A3A6AC4429E10, extendedRequestId=9GFyFnFahMZN2S68ylTW7Y88ajWLXhZEE4eGDJUmxhgkmMAVyrgNmjF6s1jY+1crQOSk/sHzP4c=, cfId=undefined, statusCode=404, retryable=false, retryDelay=47.881774482908625
error: Error handling MECA export failure message=getaddrinfo ENOTFOUND None None:587, stack=Error: getaddrinfo ENOTFOUND None None:587

```
-----
Depends on #1373 #1374

When these are complete clicking `Next` should validate and return an error when file upload is still in progress. The result of such an error should be displayed to the user as below:

![image](https://user-images.githubusercontent.com/8524685/51535598-d1e9a000-1e40-11e9-8c17-eb8e6f8578e7.png)

**Comment by diversemix** [comment]
First commit will be to generate a validation error on the manuscript if any file is not in the `STORED` state

**Comment by diversemix** [comment]
We also need to check that the manuscript source file is not of type `MANUSCRIPT_SOURCE_PENDING`
