### ISSUE TITLE
Export issue in Production - no MECA file generated

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#1568]
email:
```
Manuscript ID: 247f8a38-888e-4d8f-a0f7-a96c65ccefb0
Manuscript title: Sensor I regulated ATPase activity of FleQ is essential for maintaining the monotrichous 1 status of Pseudomonas aeruginosa
Error:

NoSuchKey: The specified key does not exist.
```

Logs:
```
{"level":"info","message":"Saved AuditLog with UUID abad8f1a-6f0e-425d-96dd-85efe3be1d90","timestamp":"2019-02-22T13:27:47.688Z"}
{"manuscriptId":"247f8a38-888e-4d8f-a0f7-a96c65ccefb0","level":"info","message":"Starting MECA export","timestamp":"2019-02-22T13:27:47.809Z"}
{"level":"info","message":"Bad auth token","timestamp":"2019-02-22T13:27:47.860Z"}
{"message":"MECA export failed","stack":"NoSuchKey: The specified key does not exist.\n    at Request.extractError (/home/xpub/node_modules/aws-sdk/lib/services/s3.js:582:35)\n    at Request.callListeners (/home/xpub/node_modules/aws-sdk/lib/sequential_executor.js:109:20)\n    at Request.emit (/home/xpub/node_modules/aws-sdk/lib/sequential_executor.js:81:10)\n    at Request.emit (/home/xpub/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/home/xpub/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/home/xpub/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /home/xpub/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/home/xpub/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/home/xpub/node_modules/aws-sdk/lib/request.js:685:12)\n    at Request.callListeners (/home/xpub/node_modules/aws-sdk/lib/sequential_executor.js:119:18)\n    at Request.emit (/home/xpub/node_modules/aws-sdk/lib/sequential_executor.js:81:10)\n    at Request.emit (/home/xpub/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/home/xpub/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/home/xpub/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /home/xpub/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/home/xpub/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/home/xpub/node_modules/aws-sdk/lib/request.js:685:12)\n    at Request.callListeners (/home/xpub/node_modules/aws-sdk/lib/sequential_executor.js:119:18)\n    at callNextListener (/home/xpub/node_modules/aws-sdk/lib/sequential_executor.js:99:12)\n    at IncomingMessage.onEnd (/home/xpub/node_modules/aws-sdk/lib/event_listeners.js:294:13)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)","code":"NoSuchKey","region":null,"name":"NoSuchKey","time":"2019-02-22T13:27:47.900Z","requestId":"002B004C62F79535","extendedRequestId":"v35pylqV0ZOhTE+uFSJCQbLd9N6FEE8tfkU8V6867TFcHhX/Xu11vOluJptsCoo9knAg/m8kXUA=","statusCode":404,"retryable":false,"retryDelay":37.844707241345056,"level":"error","timestamp":"2019-02-22T13:27:47.901Z"}
```

**Comment by diversemix** [comment]
Database:

```
                  id                  |            manuscript_id             |          created           |          updated           |           type            | label |       filename        |                       url                        |    mime_type    | size | status  
--------------------------------------+--------------------------------------+----------------------------+----------------------------+---------------------------+-------+-----------------------+--------------------------------------------------+-----------------+------+---------
 a5f081d9-98c0-4c51-926e-4d92bbac59c2 | 247f8a38-888e-4d8f-a0f7-a96c65ccefb0 | 2019-02-22 09:25:47.873+00 | 2019-02-22 13:27:47.971+00 | MANUSCRIPT_SOURCE         |       | FleQ_Elife_220219.pdf | manuscripts/247f8a38-888e-4d8f-a0f7-a96c65ccefb0 | application/pdf |      | STORED
 2d7a681e-06b3-4d15-b0fe-09e712a0be61 | 247f8a38-888e-4d8f-a0f7-a96c65ccefb0 | 2019-02-22 09:10:07.209+00 | 2019-02-22 13:27:47.971+00 | MANUSCRIPT_SOURCE_PENDING |       | FleQ_Elife_220219.pdf | manuscripts/247f8a38-888e-4d8f-a0f7-a96c65ccefb0 | application/pdf |      | CREATED
 d7bdd31c-86f9-49da-bbb2-98df99e40f6f | 247f8a38-888e-4d8f-a0f7-a96c65ccefb0 | 2019-02-22 08:57:06.173+00 | 2019-02-22 13:27:47.971+00 | MANUSCRIPT_SOURCE_PENDING |       | FleQ_Elife_220219.pdf | manuscripts/247f8a38-888e-4d8f-a0f7-a96c65ccefb0 | application/pdf |      | CREATED
(3 rows)
```

**Comment by diversemix** [comment]
I plan on deleteing the rows from the file table `2d7a681e-06b3-4d15-b0fe-09e712a0be61` and `d7bdd31c-86f9-49da-bbb2-98df99e40f6f` 

We now need a way of re-exporting this submission:

```
elifexpubprod=> select id,status from manuscript where id='247f8a38-888e-4d8f-a0f7-a96c65ccefb0';
                  id                  |       status       
--------------------------------------+--------------------
 247f8a38-888e-4d8f-a0f7-a96c65ccefb0 | MECA_EXPORT_FAILED
```

**Comment by diversemix** [comment]
Rogue files now deleted:

```
elifexpubprod=> select id,status,type from file where manuscript_id='247f8a38-888e-4d8f-a0f7-a96c65ccefb0';
                  id                  | status  |           type            
--------------------------------------+---------+---------------------------
 a5f081d9-98c0-4c51-926e-4d92bbac59c2 | STORED  | MANUSCRIPT_SOURCE
 2d7a681e-06b3-4d15-b0fe-09e712a0be61 | CREATED | MANUSCRIPT_SOURCE_PENDING
 d7bdd31c-86f9-49da-bbb2-98df99e40f6f | CREATED | MANUSCRIPT_SOURCE_PENDING
(3 rows)

elifexpubprod=> delete from file where id='2d7a681e-06b3-4d15-b0fe-09e712a0be61';
DELETE 1
elifexpubprod=> delete from file where id='d7bdd31c-86f9-49da-bbb2-98df99e40f6f';
DELETE 1
elifexpubprod=> select id,status,type from file where manuscript_id='247f8a38-888e-4d8f-a0f7-a96c65ccefb0';
                  id                  | status |       type        
--------------------------------------+--------+-------------------
 a5f081d9-98c0-4c51-926e-4d92bbac59c2 | STORED | MANUSCRIPT_SOURCE
(1 row)
```

**Comment by diversemix** [comment]
Ran in production:
```
elife@prod--xpub:~$ !doc
docker exec -it xpub_app_1 bash
root@441c47ded8a7:~# ls scripts/mecaExport.js 
scripts/mecaExport.js
root@441c47ded8a7:~# node scripts/mecaExport.js 247f8a38-888e-4d8f-a0f7-a96c65ccefb0
info: Starting MECA export manuscriptId=247f8a38-888e-4d8f-a0f7-a96c65ccefb0
info: Uploading MECA archive to SFTP manuscriptId=247f8a38-888e-4d8f-a0f7-a96c65ccefb0
info: Uploading MECA archive to S3 manuscriptId=247f8a38-888e-4d8f-a0f7-a96c65ccefb0
info: Saved AuditLog with UUID eb0556ed-bdd4-4204-830f-c6234c94cadb
Manuscript 247f8a38-888e-4d8f-a0f7-a96c65ccefb0 successfully exported
Export complete!
root@441c47ded8a7:~# 

```

/cc @hdrury1 / @jyenes
