### ISSUE TITLE
Inconsistent failure of browser tests on CI

### ISSUE THREAD

**Issue by will-byrne** [elifesciences/elife-xpub#1907]
**Describe the bug**
When running the browser tests on the CI there is an inconsistent test failure which can be gotten around by simply rerunning the tests.

Happy Path test
```
1) Error on page

"http://localhost:4000/submit/7eeb6c23-73ba-4265-ac4d-1a2a1a568885/disclosure":

   GraphQL error: Manuscript has no source file

   Browser: HeadlessChrome 73.0.3683 / Linux 0.0.0
   Screenshot:

/tmp/screenshots/2019-04-09_10-29-12/test-7/HeadlessChrome_73.0.3683_Linux_0.0.0/errors/1.png

      138 |  async submit() {
      139 |    await this.t.click(wizardStep.submit)
      140 |  }
      141 |
      142 |  async accept() {
    > 143 |    await this.t.click(wizardStep.accept)
      144 |  }
      145 |
      146 |  async thankyou() {
      147 |    await this.t.click(thankyou.finish)
      148 |  }

      at click (/home/xpub/test/helpers/navigationHelper.js:143:18)
      at NavigationHelper.accept
   (/home/xpub/test/helpers/navigationHelper.js:142:18)
      at accept (/home/xpub/test/submission.browser.js:141:20)
```

**Steps To Reproduce**
Run browser tests on the CI

**Expected behavior**
Consistent passing and failing

**Device, Operating System and Browser**
CI

**Comment by Cooryd** [comment]
Inconclusive results after testing. We're currently spliting the application build and browser tests so will re-investigate after that change.
