### ISSUE TITLE
Investigate intermittent data integrity error on disclosure step

### ISSUE THREAD

**Issue by Cooryd** [elifesciences/elife-xpub#1995]
Investigate any part of the submit process which happens at the disclosure step of the wizard which could be throwing the following intermittent error on the pipelines browser tests:

```
53.757Z] (node:942) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-05-16T19:27:53.757Z] (node:942) UnhandledPromiseRejectionWarning: #<Object>
[2019-05-16T19:27:53.757Z] (node:942) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[2019-05-16T19:27:53.757Z]  ✖ Ability to progress through the wizard is tied to validation (screenshots:
[2019-05-16T19:27:53.757Z]  /tmp/screenshots/2019-05-16_19-20-40/test-8)
[2019-05-16T19:27:53.757Z] 
[2019-05-16T19:27:53.757Z]    1) Error on page
[2019-05-16T19:27:53.757Z] 
[2019-05-16T19:27:53.757Z]    "http://app:3000/submit/2ef3da2d-82a7-4cd5-96fe-bc51e7dd401b/disclosure":
[2019-05-16T19:27:53.757Z] 
[2019-05-16T19:27:53.757Z]       GraphQL error: Data Integrity Error property updated set to Thu May
[2019-05-16T19:27:53.757Z]       16 2019 19:27:35 GMT+0000 (UTC): is older than the one stored in the
[2019-05-16T19:27:53.757Z]       database!
[2019-05-16T19:27:53.757Z] 
[2019-05-16T19:27:53.757Z]       Browser: HeadlessChrome 74.0.3729 / Linux 0.0.0
[2019-05-16T19:27:53.757Z]       Screenshot:
[2019-05-16T19:27:53.757Z] 
[2019-05-16T19:27:53.757Z]    /tmp/screenshots/2019-05-16_19-20-40/test-8/HeadlessChrome_74.0.3729_Linux_0.0.0/errors/1.png
[2019-05-16T19:27:53.757Z] 
[2019-05-16T19:27:53.757Z]          157 |    // wait for "accept" button to show
[2019-05-16T19:27:53.757Z]          158 |    await this.waitForElement('accept')
[2019-05-16T19:27:53.757Z]          159 |  }
[2019-05-16T19:27:53.757Z]          160 |
[2019-05-16T19:27:53.757Z]          161 |  async accept() {
[2019-05-16T19:27:53.757Z]        > 162 |    await this.t.click(wizardStep.accept, OPTS)
[2019-05-16T19:27:53.757Z]          163 |    // wait for "finish" button to show
[2019-05-16T19:27:53.757Z]          164 |    await this.waitForElement('finish')
[2019-05-16T19:27:53.757Z]          165 |  }
[2019-05-16T19:27:53.757Z]          166 |
[2019-05-16T19:27:53.757Z]          167 |  async thankyou() {
[2019-05-16T19:27:53.757Z] 
[2019-05-16T19:27:53.757Z]          at click (/home/xpub/test/helpers/navigationHelper.js:162:18)
[2019-05-16T19:27:53.757Z]          at NavigationHelper.accept
[2019-05-16T19:27:53.757Z]       (/home/xpub/test/helpers/navigationHelper.js:161:18)
[2019-05-16T19:27:53.757Z]          at accept (/home/xpub/test/submission.browser.js:242:20)
```

**Comment by Cooryd** [comment]
Looks like ORM based issue again.
