### ISSUE TITLE
Dying Containers do not fail the pipeline

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#2195]
If a container dies in the pipeline then it passes.

We need to add to the pipeline a check that the container did what was expected of it 

see #2081 #2131

**Comment by jure** [comment]
Happened again during what appears to be a normal run, i.e. not the container dying?

https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Felife-xpub/detail/PR-2131/24/pipeline/40

```

[2019-06-28T10:03:31.025Z] + IMAGE_TAG=8d7bdf9098384f1b30b90f072c4f0df84dce78f6 NODE_ENV=production NODE_CONFIG_ENV=unit-test docker-compose -f docker-compose.yml -f docker-compose.ci.yml run --rm --name elife-xpub_app_test app npm test
[2019-06-28T10:03:31.365Z] Starting elife-xpub_api-dummy_1 ... 
[2019-06-28T10:03:31.365Z] Starting elife-xpub_sftp_1      ... 
[2019-06-28T10:03:31.365Z] 
Starting elife-xpub_api-dummy_1 ... done
Starting elife-xpub_postgres_1  ... 
[2019-06-28T10:03:31.365Z] 
Starting elife-xpub_sftp_1      ... done
Starting elife-xpub_fakes3_1    ... 
[2019-06-28T10:03:32.642Z] 
Starting elife-xpub_postgres_1  ... done
Starting elife-xpub_fakes3_1    ... done
[2019-06-28T10:03:32.642Z] > xpub-elife@1.0.0 test /home/xpub
[2019-06-28T10:03:32.642Z] > NODE_CONFIG_ENV=unit-test jest --runInBand
[2019-06-28T10:03:32.642Z] 
[2019-06-28T10:04:01.046Z] PASS component-model-manuscript packages/component-model-manuscript/entities/manuscript/index.test.js (12.336s)
[2019-06-28T10:04:01.046Z] PASS component-submission-server packages/component-submission/server/aggregates/Submission.test.js
[2019-06-28T10:04:07.299Z] PASS component-submission-server packages/component-submission/server/resolvers/submitManuscript.test.js (6.969s)
[2019-06-28T10:04:20.967Z] PASS component-submission-client packages/component-submission/client/pages/EditorsStepPage.test.js (11.048s)
[2019-06-28T10:04:21.339Z] PASS component-submission-client packages/component-submission/client/utils/ValidationSchemas.test.js
[2019-06-28T10:04:24.555Z] error:  message=Data Integrity Error property updated set to Fri Jun 28 2019 10:04:23 GMT+0000 (UTC): is older than the one stored in the database!, stack=Error: Data Integrity Error property updated set to Fri Jun 28 2019 10:04:23 GMT+0000 (UTC): is older than the one stored in the database!
[2019-06-28T10:04:24.555Z]     at integrityError (/home/xpub/node_modules/@pubsweet/base-model/src/index.js:15:3)
[2019-06-28T10:04:24.555Z]     at protectedSave (/home/xpub/node_modules/@pubsweet/base-model/src/index.js:129:17)
[2019-06-28T10:04:24.555Z]     at <anonymous>
[2019-06-28T10:04:24.555Z] PASS component-model packages/component-model/model.test.js
[2019-06-28T10:04:27.045Z] PASS component-submission-client packages/component-submission/client/pages/FilesStepPage.test.js
[2019-06-28T10:04:32.134Z] error: S3.putContent::start Error: Failed to persist file | 66847033-ecdd-4ca2-b130-78fb4cedcb96
[2019-06-28T10:04:32.134Z] error: uploadManuscriptFile threw this error: Error: Failed to persist file
[2019-06-28T10:04:33.963Z] PASS component-submission-server packages/component-submission/server/resolvers/uploadManuscript.test.js (6.871s)
[2019-06-28T10:04:38.047Z] PASS component-submission-client packages/component-submission/client/components/PeoplePicker/PeoplePickerLogic.test.js
[2019-06-28T10:04:38.423Z] PASS component-submission-server packages/component-submission/server/use-cases/helpers/files.test.js
[2019-06-28T10:04:41.593Z] PASS component-submission-client packages/component-submission/client/pages/SubmissionWizard.test.js
```

Output just stops after that last line and the script says it completed successfully.

**Comment by giorgiosironi** [comment]
Any recent output that is still in Jenkins (open PR rather than closed, or mainline build like `develop`)?

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/elife-xpub/pull/2251 will fix this.

**Comment by diversemix** [comment]
@giorgiosironi ... are you sure? Will fix this if we have the same issue again how will it stop it looking green when it has failed? ... I think we should put a test in at the end to check the task has fully completed (we could check for the Test Summary)  - This way we can confirm the task has completed all that was required of it. What do you think?

**Comment by giorgiosironi** [comment]
The immediate problem being fixed is the cause for the container terminating early with a 0 exit code, I agree that to defend against unknown unknowns an independent check should be performed over the unit test results. Let's see what logs can Jest produce.

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/elife-xpub/pull/2255 ready (executing some more runs).

**Comment by diversemix** [comment]
Added an example script to #2255 ... so going to close this in favour of that going in.
