### ISSUE TITLE
Investigate database error in logs

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#2356]
```
{"error":{"name":"error","length":308,"severity":"ERROR","code":"23503","detail":"Key (id)=(b41cf42e-a139-4a50-a33d-c6b374cc282d) is still referenced from table \"file\".","schema":"public","table":"file","constraint":"file_manuscript_id_fkey","file":"ri_triggers.c","line":"3280","routine":"ri_ReportViolation","originalStack":"error: update or delete on table \"manuscript\" violates foreign key constraint \"file_manuscript_id_fkey\" on table \"file\"\n at Connection.parseE (/home/xpub/node_modules/pg/lib/connection.js:602:11)\n at Connection.parseMessage (/home/xpub/node_modules/pg/lib/connection.js:399:19)\n at Socket. (/home/xpub/node_modules/pg/lib/connection.js:121:22)\n at emitOne (events.js:116:13)\n at Socket.emit (events.js:211:7)\n at addChunk (_stream_readable.js:263:12)\n at readableAddChunk (_stream_readable.js:250:11)\n at Socket.Readable.push (_stream_readable.js:208:10)\n at TCP.onread (net.js:601:20)"},"level":"error","message":"delete from \"manuscript\" where \"manuscript\".\"id\" = $1 - update or delete on table \"manuscript\" violates foreign key constraint \"file_manuscript_id_fkey\" on table \"file\"","timestamp":"2019-08-15T08:38:36.301Z"}
```

**Comment by diversemix** [comment]
Queried the database and the id does not exist on the `manuscript` table or referenced by the `file` table. I would guess that the user pressed "delete" again and it got removed. Everything looks ok.

Closing this @hdrury1 ... shout if you have any questions.
