### ISSUE TITLE
Re-enable and Investigate / fix SFTP test failure

### ISSUE THREAD

**Issue by diversemix** [elifesciences/elife-xpub#657]
Now and then we get this failure

see: https://gitlab.com/elifesciences/elife-xpub/-/jobs/100758570
```

   1) AssertionError: expected 0 to deeply equal 1

      Browser: HeadlessChrome 67.0.3396 / Linux 0.0.0
      Screenshot:

   /home/xpub/test/screenshots/2018-09-24_08-07-58/test-2/HeadlessChrome_67.0.3396_Linux_0.0.0/errors/1.png

         150 |    .eql(manuscript.title)
         151 |    .expect(dashboard.stages.textContent)
         152 |    .eql('QA')
         153 |
         154 |  // SFTP server
       > 155 |  await autoRetry(() =>
      t.expect(mockFs.readdirSync('/test').length).eql(1))
         156 |  server.close()
         157 |})
         158 |
         159 |test('Ability to progress through the wizard is tied to
      validation', async t => {
         160 |  replaySetup('success')

         at eql (/home/xpub/test/submission.e2e.js:155:70)
         at fn (/home/xpub/test/submission.e2e.js:31:20)
```

**Comment by hdrury1** [comment]
We have decided to disbale this part of the test for now, so renaming the issue accordingly.

**Comment by hdrury1** [comment]
@diversemix did this ever get resolved?
